apiVersion: apps/v1
kind: Deployment
metadata:
  name: shelf-layout-management
  labels:
    app: shelf-layout-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shelf-layout-management
  template:
    metadata:
      labels:
        app: shelf-layout-management
    spec:
      containers:
      - name: shelf-layout-management
        image: Local/shelflayoutmanagementserver:latest
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: shelf-layout-management-service
spec:
  selector:
    app: shelf-layout-management
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
